name: Trigger auto deployment for studentcontainer2024

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/studentcontainer2024-AutoDeployTrigger-0488b821-c3be-46d5-8a91-b9c0cf8d3f2e.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.STUDENTCONTAINER2024_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: hub.docker.com/repository/docker/madhusudhan9981/dockerdemo/general
          registryUsername: ${{ secrets.STUDENTCONTAINER2024_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.STUDENTCONTAINER2024_REGISTRY_PASSWORD }}
          containerAppName: studentcontainer2024
          resourceGroup: aks-cont-rg2024
          imageToBuild: hub.docker.com/repository/docker/madhusudhan9981/dockerdemo/general/studentcontainer2024:${{ github.sha }}
          
            

     

